### ISSUE TITLE
Installation Error libculibos.a(cuos_common_posix.o)

### ISSUE THREAD

**Issue by sxzhang1993** [gpgpu-sim/pytorch-gpgpu-sim#7]
## Issue description

Hello I have problems when running setup.py. I have followed the installation guide on the pytorch-gpgpu-sim homepage.

## Code example
[ 95%] Linking CXX executable ProcessGroupGlooTest
[100%] Linking CXX executable ProcessGroupGlooAsyncTest
/usr/bin/ld: /usr/local/cuda/lib64/libculibos.a(cuos_common_posix.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
test/CMakeFiles/ProcessGroupGlooTest.dir/build.make:110: recipe for target 'test/ProcessGroupGlooTest' failed
make[2]: *** [test/ProcessGroupGlooTest] Error 1
CMakeFiles/Makefile2:244: recipe for target 'test/CMakeFiles/ProcessGroupGlooTest.dir/all' failed
make[1]: *** [test/CMakeFiles/ProcessGroupGlooTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: /usr/local/cuda/lib64/libculibos.a(cuos_common_posix.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
test/CMakeFiles/ProcessGroupGlooAsyncTest.dir/build.make:110: recipe for target 'test/ProcessGroupGlooAsyncTest' failed
make[2]: *** [test/ProcessGroupGlooAsyncTest] Error 1
CMakeFiles/Makefile2:282: recipe for target 'test/CMakeFiles/ProcessGroupGlooAsyncTest.dir/all' failed
make[1]: *** [test/CMakeFiles/ProcessGroupGlooAsyncTest.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack nccl caffe2 nanopb libshm gloo THD c10d'

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

CUDA 8.0/9.0/9.1
CUDNN 7.0/7.1
will all have this error.

Any help would be appreciated! Thanks so much!

**Comment by baiyang100** [comment]
Brother, have you solved your problem?I'm running into the same issue, Ubuntu 18.04 install cuda8,cudnn7.1.3, if you fix it, can you share the solution?

**Comment by IceCY** [comment]
I comment out the following lines in `torch/lib/c10d/test/CMakeLists.txt` to bypass the compilation issue.
```
c10d_add_test(ProcessGroupGlooTest.cpp c10d c10d_cuda_test)
c10d_add_test(ProcessGroupGlooAsyncTest.cpp c10d c10d_cuda_test)
```

System: Ubuntu 18.04;  CUDA 8; CUDNN 7.1.4

**Comment by sxzhang1993** [comment]
> Brother, have you solved your problem?I'm running into the same issue, Ubuntu 18.04 install cuda8,cudnn7.1.3, if you fix it, can you share the solution?

Hello, I have tried IceCY's method and it worked for me!

**Comment by sxzhang1993** [comment]
> I comment out the following lines in `torch/lib/c10d/test/CMakeLists.txt` to bypass the compilation issue.
> 
> ```
> c10d_add_test(ProcessGroupGlooTest.cpp c10d c10d_cuda_test)
> c10d_add_test(ProcessGroupGlooAsyncTest.cpp c10d c10d_cuda_test)
> ```
> 
> System: Ubuntu 18.04; CUDA 8; CUDNN 7.1.4

Thanks a lot! Now I have it installed by following your solution.

**Comment by baiyang100** [comment]
> I comment out the following lines in `torch/lib/c10d/test/CMakeLists.txt` to bypass the compilation issue.
> 
> ```
> c10d_add_test(ProcessGroupGlooTest.cpp c10d c10d_cuda_test)
> c10d_add_test(ProcessGroupGlooAsyncTest.cpp c10d c10d_cuda_test)
> ```
> 
> System: Ubuntu 18.04; CUDA 8; CUDNN 7.1.4

Thanks a lot! Now I have it installed by following your solution.But I ran into a new problem while running the mnists dataset.
